# Codecov Configuration
# https://docs.codecov.com/docs/codecov-yaml

coverage:
  status:
    project:
      default:
        target: 80%           # Target coverage percentage
        threshold: 2%         # Allow 2% drop before failing
        if_ci_failed: error   # Fail if CI fails
    patch:
      default:
        target: 70%           # New code should have 70% coverage
        threshold: 5%         # Allow 5% drop for patches

  precision: 2                # Decimal places for coverage
  round: down                 # Round down coverage percentages

comment:
  layout: "reach,diff,flags,tree,footer"
  behavior: default           # Post comment on PRs
  require_changes: false      # Always comment
  require_base: false         # Comment even without base
  require_head: true          # Require head report

ignore:
  - "**/__tests__/**"         # Ignore test files
  - "**/*.test.ts"
  - "**/*.test.tsx"
  - "**/*.spec.ts"
  - "**/tests/**"
  - "vite.config.ts"
  - "vitest.config.ts"
  - "playwright.config.ts"
  - "dist/**"
  - "node_modules/**"

flags:
  unittests:
    paths:
      - src/
    carryforward: true        # Carry forward if upload fails

github_checks:
  annotations: true           # Add annotations to PR

