services:
  # Development service with hot reload
  hvac-canvas-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: hvac-canvas-dev
    ports:
      - "5174:5174"
    volumes:
      # Mount source code for hot reload
      - ./src:/app/src:ro
      - ./public:/app/public:ro
      - ./index.html:/app/index.html:ro
      - ./vite.config.ts:/app/vite.config.ts:ro
      - ./tsconfig.json:/app/tsconfig.json:ro
      # Exclude node_modules to avoid conflicts
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_HOST=0.0.0.0
      - VITE_PORT=5174
    networks:
      - hvac-network
    restart: unless-stopped
    profiles:
      - dev

  # Production service with optimized build
  hvac-canvas-prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: hvac-canvas-prod
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    networks:
      - hvac-network
    restart: unless-stopped
    profiles:
      - prod

  # Alternative production service on different port
  hvac-canvas-prod-alt:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: hvac-canvas-prod-alt
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production
    networks:
      - hvac-network
    restart: unless-stopped
    profiles:
      - prod-alt

networks:
  hvac-network:
    driver: bridge

# Optional: Add volumes for persistent data if needed in the future
volumes:
  node_modules:
